POST http://localhost:8080/class HTTP/1.1
content-Type: application/json

{
  "name":"SY43",
  "description":"UV de développement Android, délicieusement gérer par Brisset Bebou",
  "color":"#ff9130"
}
