POST http://localhost:8080/res HTTP/1.1
content-Type: application/json

{
  "class" : "1",
  "path" : "html 1",
  "type" : ".html",
  "filedata" : "PGgxPkhlbGxvIHRoZXJlICE8L2gxPgo8cD5JJ20gdHJ5aW5nIHNvbWV0aGluZyBoZXJlIDspPC9wPg=="
}
